Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2023-11, with the labels that each got.

#127 [Chore] ProgressView 수정
  ABloom/ABloom.xcodeproj/xcshareddata/xcschemes/ABloom.xcscheme
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
Labels: Chore

#130 [Chore/#129] 사진라이브러리 접근 권한 문구 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
Labels: Chore

#133 [Feat] Provisioning Profile 추가
  ABloom/ABloom.xcodeproj/project.pbxproj
Labels: Feat, 🚨 Emergency

#134 [Bug/#132] SwipeBack 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
Labels: Bug

#136 [Chore] 버전 업데이트 -> v1.0.1
  ABloom/ABloom.xcodeproj/project.pbxproj
Labels: Chore

#140 [Bug/#139] 남성일 때, ChatBubble 딜레이 ProgressView로 해결
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
Labels: Bug, 👀 Review Needed

#150 [Feat/#146] 고객센터 및 질문제작소 웹 링크 수정
  ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
Labels: Feat, 🌱 Simple, 👀 Review Needed

#145 [Bug/#144] SelectQuestionView 질문 오름차순 정렬
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
Labels: Bug, 🌱 Simple, 👍🏻 Merge Needed

#154 [ Bug/#131] 추천질문 변경 날짜 한국시간으로 수정
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
Labels: Bug

#138 [Bug/#137] Splash Constraint 추가
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Launch Screen.storyboard
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Contents.json
Labels: Bug, 👀 Review Needed

#156 [Ref/#153] ChatBubble 성별에 따른 분기처리 컴포넌트 내에서 해결
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Ref, 💬 Answer Needed

#157 [Ref/#128] AppDelegate 읽고 주석처리
  ABloom/ABloom/AppDelegate.swift
Labels: Ref, 🌱 Simple

#160 [Bug/#155] 결혼예정일 디데이 UTC 한국 날짜 계산
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
Labels: Bug, 👀 Review Needed

#159 [Feat/#159] 로컬 푸쉬 기능 구현, 내용은 미확정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Info.plist
  ABloom/ABloom/LocalPushNotification.swift
Labels: Feat

#142 [Bug/#141] 카테고리 변경시 상단으로 스크롤
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
Labels: Bug, Design, 👀 Review Needed

#143 [Feat/#135] 홈뷰 레이아웃 수정, 상대방 성별 불러오기
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
Labels: Bug, Feat, 👀 Review Needed

#162 [Bug/#161] 성별에 따른 초상화 이미지 변경 기능 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Resources/Utilities/UserSexType.swift
Labels: Bug, Feat, 👀 Review Needed

#165 [Ref&Feat/#164] 원격, 로컬 알림 파일 합치기 & 로컬푸쉬 시간 변경
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/LocalPushNotification.swift
Labels: Feat, Ref

#169 [Bug] QA 반영 Keyboard 숨기기, 회원탈퇴 로직 일부 수정
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
Labels: Bug

#167 [Bug/#166] 결혼날짜 디데이 버그 수정
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
Labels: Bug, 🌱 Simple, 👀 Review Needed

#171 [Bug] 고객 센터 URL 수정
  ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
Labels: Feat

#173 [Bug] 고객 센터 URL 수정
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/WebView.swift
  ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
Labels: Bug

#174 [Feat] 버전 업데이트 -> 1.0.2
  ABloom/ABloom.xcodeproj/project.pbxproj
Labels: Feat

#168 [Bug/#166] 결혼날짜 디데이 버그 수정
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
Labels: Bug, 🌱 Simple, 👀 Review Needed

#175 [Design/#163] sprint2 챗버블 컴포넌트 추가 및 수정 & 뷰에 수정사항 적용
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@3x.png
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Extensions/Ex+Font.swift
Labels: Design, Chore, 🚨 Emergency

#177 [ v1.0.2] 버그 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/xcshareddata/xcschemes/ABloom.xcscheme
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Info.plist
  ABloom/ABloom/Launch Screen.storyboard
  ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/WebView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Contents.json
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Components/InputFields.swift
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
  ABloom/ABloom/Resources/Extensions/Ex+UIApplication.swift
  ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
  ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
  ABloom/ABloom/Resources/Utilities/UserSexType.swift
Labels: Feat

#180 [Feat/#179] 리액션 기능 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Resources/Utilities/ReactionType.swift
Labels: Feat, 👀 Review Needed

#183 [Feat/#179] 리액션 및 문답 완성 로직 구현
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Resources/Utilities/ReactionType.swift
Labels: Feat, 👀 Review Needed

#181 [ Design/#172] 문답리스트 뷰 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
  ABloom/ABloom/Resources/Utilities/Category.swift
Labels: Design, 👀 Review Needed

#184 [Feat/#176] AnswerWriteView 텍스트필드 및 스와이프 제한 적용
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
Labels: Bug, Feat

#189 [ Design/#182] 문답 확인 뷰 레이아웃 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
Labels: Design, 👀 Review Needed

#188 [Feat/#185] SelectQuestionView 글자 개행 도입 및 패딩 일부 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Extensions/Ex+String.swift
Labels: Feat

#191 [Feat/#190] QuestionMainViewModel 문답 완성상태 조건 추가
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
Labels: Feat, 🌱 Simple, 👀 Review Needed

#193 [Feat] 완성된 QnA 개수 로직 수정
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
Labels: Feat, 👀 Review Needed

#195 [Bug/#149] 로그아웃 플로우 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/TabBar/TabBarView.swift
Labels: Feat, 👀 Review Needed

#196 [Feat/192] 문답확인뷰 반응로직 수정
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Design, 👀 Review Needed

#198 [Design/#197] Tipview 레이아웃 수정
  ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
Labels: Design, 🌱 Simple, 👀 Review Needed

#201 [Bug/#199] 스와이프 재활성화
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
Labels: Bug

#204 [Design/#186] minWidth 값 수정
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Design

#206 [Design/#205] ChatBtn 크기 및 폰트 수정
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Design

#209 [Feat/#207] 완성하지 않아도 작성한 문답 개수를 홈화면에 표시
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
Labels: Feat, 👀 Review Needed

#210 [Feat/#208] 반응에 따른 푸쉬노티 구현
  ABloom/functions/index.js
  FirebaseFunction/functions/index.js
Labels: Feat

#211 [Feat/#200] 문답확인뷰 Scroll 적용
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
Labels: Feat

#214 [Feat/#212] 문답확인뷰 반응 업데이트 로직 재수정
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Design, 👀 Review Needed

#216 [Bug] QA 해결, 로그아웃 시 로그인 화면이 두 개가 표시되는 문제 해결
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
Labels: Bug

#217 [Bug] 숫자 포함시 줄바꿈 현상 해결
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Extensions/Ex+String.swift
Labels: Bug

#218 [Bug] print문 삭제
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Bug

#220 [v1.1.0] 배포완료
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Extensions/Ex+String.swift
Labels: Feat, 👀 Review Needed

#219 [v1.1.0] 배포완료
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Firebase/Model/DBUserModel.swift
  ABloom/ABloom/Info.plist
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/TabBar/TabBarView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/noticeIcon.imageset/noticeIcon@3x.png
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Extensions/Ex+Font.swift
  ABloom/ABloom/Resources/Extensions/Ex+String.swift
  ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
  ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
  ABloom/ABloom/Resources/Utilities/Category.swift
  ABloom/ABloom/Resources/Utilities/ReactionType.swift
  FirebaseFunction/.firebaserc
  FirebaseFunction/.gitignore
  FirebaseFunction/firebase.json
  FirebaseFunction/firestore.indexes.json
  FirebaseFunction/firestore.rules
  FirebaseFunction/functions/.eslintrc.js
  FirebaseFunction/functions/.gitignore
  FirebaseFunction/functions/index.js
  FirebaseFunction/functions/package.json
Labels: Feat, 👀 Review Needed

#221 [Ref] 리팩토링을 위한 준비
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginMD.md
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginViewModel.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/SubViews/AppleLoginButtonViewRepresentable.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ImageFileManager.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/EmbedWebView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/MenuListItem.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/MenuListNavigationItem.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/ToastView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/WebView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/PolicyView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/NavigationModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/Tab.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarMD.md
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/WebView/WebView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingView.swift
  ABloom/ABloom/Presentation/SignIn/SignInView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpView.swift
Labels: Feat, Design, Ref

#223 [Design/#222] Gray Color Asset 추가
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 100.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 200.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 300.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 400.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 50.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 500.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 600.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 700.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 800.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 900.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 950.colorset/Contents.json
Labels: Design

#226 [Ref] 모델 구조 잡기
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/EssentialQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView2.0.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionView2.0.swift
  ABloom/ABloom/Presentation/Main/Menu/WebView/WebView.swift
  ABloom/ABloom/Presentation/Main/Menu/WebView/WebView2.0.swift
Labels: Ref, 👀 Review Needed

#232 [Ref/#224] 오류 파일 주석 처리 -> 추후 리아가 해결할 예정 + 회원가입 뷰 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/Menu/WebView/ShowWebView.swift
  ABloom/ABloom/Presentation/SignUp/EmbedWebView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
  ABloom/ABloom/Resources/Components/Buttons.swift
  ABloom/ABloom/Resources/Extensions/Ex+Sequence.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
  ABloom/ABloom/Resources/Utilities/SignUpStep.swift
  ABloom/ABloom/Resources/Utilities/UserSexType.swift
  ABloom/ABloom/Resources/Utilities/WebView.swift
Labels: Feat, Ref, 👀 Review Needed

#234 [Design/#233] QnAListItem 컴포넌트 디자인 적용
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift
  ABloom/ABloom/Resources/Assets.xcassets/colors/StatusColor/Complete.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/StatusColor/Contents.json
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
  ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
Labels: Design, 👀 Review Needed

#237 [Feat/#235] 온보딩 레이아웃 완료
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingPageView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingTabView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingView.swift
Labels: Feat

#241 [Design/#240] QnAListView 디자인 적용
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/profile.circle.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/profile.circle.imageset/user_icon.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/profile.circle.imageset/user_icon@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/profile.circle.imageset/user_icon@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/colors/Background/Background.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Background/Contents.json
Labels: Feat, Design, 👀 Review Needed

#249 [Feat/#243] Profile Menu 뷰 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/EssentialQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/FemaleAvatar.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/FemaleAvatar.imageset/Female @1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/FemaleAvatar.imageset/Female @2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/FemaleAvatar.imageset/Female @3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/MaleAvatar.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/MaleAvatar.imageset/Male @1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/MaleAvatar.imageset/Male @2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Avartars/MaleAvatar.imageset/Male @3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/angle-right-gray.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/angle-right-gray.imageset/angle-right-gray.svg
  ABloom/ABloom/Resources/Assets.xcassets/Icons/angle-right.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/angle-right.imageset/angle-right.svg
  ABloom/ABloom/Resources/Assets.xcassets/Icons/heart_calendar.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/heart_calendar.imageset/heart_calendar.svg
  ABloom/ABloom/Resources/Utilities/MarriageStatus.swift
  ABloom/ABloom/Resources/Utilities/UserSexType.swift
Labels: Feat, 👀 Review Needed

#246 [Feat/#236] WayPoint -> SelectQ 시트 연결
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/SelectQuestionViewModel1.0.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Resources/Extensions/Ex+Color.swift
  ABloom/ABloom/Resources/Utilities/PreviewQuestions.swift
Labels: Feat

#250 [Design/#244] 문답확인뷰 디자인
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/SelectReactionView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/xmark.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/xmark.imageset/X.svg
  ABloom/ABloom/Resources/Components/Buttons.swift
Labels: Design, 👀 Review Needed

#248 [Feat/#247] WriteAnswerView 및 로직 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
Labels: Feat, Design

#255 [Feat/#252] 뷰 간 이동 구현
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
Labels: Feat

#256 [Feat/#242] 로그인뷰 디자인 적용 및 애플 로그인 기능 연결
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Presentation/SignIn/AppleLoginButtonViewRepresentable.swift
  ABloom/ABloom/Presentation/SignIn/SignInView.swift
  ABloom/ABloom/Presentation/SignIn/SignInViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Images/signInKakao.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Images/signInKakao.imageset/kakaoLiginwide.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/signInKakao.imageset/kakaoLiginwide@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/signInKakao.imageset/kakaoLiginwide@3x.png
  ABloom/ABloom/Resources/Extensions/Ex+Shape.swift
  ABloom/ABloom/Resources/Utilities/ActiveSheet.swift
Labels: Feat, Design, 👀 Review Needed

#257 [Feat/#254] Profile Menu Detail 뷰 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/WebView/ShowWebView.swift
  ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/SignUp/EmbedWebView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
Labels: Feat, 👀 Review Needed

#258 [Feat/#253] 추천질문 로직 및 질문선택 로직 일부
  ABloom/ABloom/Firebase/Firestore/EssentialQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Firebase/Model/DBEssentialQuestionModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift
Labels: Bug, Feat

#267 [Feat/#254] Connection View 뷰 및 기능 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectedView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/copy.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/copy.imageset/copy.svg
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check2.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check3.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Contents.json
  ABloom/ABloom/Resources/Components/Buttons.swift
  ABloom/ABloom/Resources/Components/InputFieldModifier.swift
  ABloom/ABloom/Resources/Components/InputFields.swift
  ABloom/ABloom/Resources/Components/NavigationArrowLeft.swift
  ABloom/ABloom/Resources/Utilities/ConnectionError.swift
Labels: Feat, 👀 Review Needed

#263 [Feat/#262] 문답리스트뷰(홈) 프로필 이미지 적용
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Utilities/UserSexType.swift
Labels: Feat, 👀 Review Needed

#266 [Feat/#265] 답변저장하는 기능 합치기
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
Labels: Bug, Feat, Design

#274 [Feat/#270] 프로필 메뉴 및 회원가입에서 가능한 입출력 동작과 뷰 간의 Source of truth를 유지할 수 있도록 로직 구현
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
Labels: Feat

#272 [Feat/#271] 로그인 팝업 홈뷰 적용, SignUpView 이동 구현
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
  ABloom/ABloom/Resources/Utilities/ActiveSheet.swift
Labels: Feat

#280 [Feat/#279] Answer Data에 대한 Snapshot Listener 구현
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
Labels: Feat, 👀 Review Needed

#275 [Feat/#269] CheckAnswerView 문답확인뷰 데이터 연결, 반응하기 기능 추가
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/SelectReactionView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/1_like.imageset/1_like@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/1_like.imageset/1_like@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/1_like.imageset/1_like@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/1_like.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/2_know.imageset/2_know@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/2_know.imageset/2_know@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/2_know.imageset/2_know@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/2_know.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/3_moreCommunication.imageset/3_needCommunication@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/3_moreCommunication.imageset/3_needCommunication@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/3_moreCommunication.imageset/3_needCommunication@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/3_moreCommunication.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/4_moreResearch.imageset/4_needKnowMore@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/4_moreResearch.imageset/4_needKnowMore@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/4_moreResearch.imageset/4_needKnowMore@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/4_moreResearch.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/5_Communicate.imageset/5_Communicate@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/5_Communicate.imageset/5_Communicate@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/5_Communicate.imageset/5_Communicate@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/5_Communicate.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/6_Good.imageset/6_Good@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/6_Good.imageset/6_Good@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/6_Good.imageset/6_Good@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/6_Good.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/7_LetsKnow.imageset/7_LetsKnow@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/7_LetsKnow.imageset/7_LetsKnow@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/7_LetsKnow.imageset/7_LetsKnow@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/7_LetsKnow.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/A_Lock.imageset/A_Lock@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/A_Lock.imageset/A_Lock@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/A_Lock.imageset/A_Lock@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/A_Lock.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/B_Add.imageset/B_Add@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/B_Add.imageset/B_Add@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/B_Add.imageset/B_Add@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/B_Add.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/C_Wait.imageset/C_Wait@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/C_Wait.imageset/C_Wait@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/C_Wait.imageset/C_Wait@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/C_Wait.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/ResponseMenu.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Reaction/ResponseMenu.imageset/ResponseMenu@SVG.svg
  ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
  ABloom/ABloom/Resources/Utilities/ReactionStatus.swift
  ABloom/ABloom/Resources/Utilities/ReactionType.swift
Labels: Feat, 👀 Review Needed

#284 [Feat/#281] 실시간 데이터 연동
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift
Labels: Feat

#283 [Feat/#276] 문답확인뷰 연결/작성 시트 띄우기
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
Labels: Feat, 🌱 Simple, 👀 Review Needed

#282 [Feat/#273] 노티 추가구현 및 네비게이션 함수구현
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
  FirebaseFunction/functions/index.js
Labels: Feat

#286 [Feat/285] 문답리스트뷰, 문답확인뷰 Answers Combine 동기화 작업, 질문에 숫자가 포함될 경우 수정
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
Labels: Feat, 👀 Review Needed

#278 [Feat/277] 카카오 로그인/로그아웃 구현
  .gitignore
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Authentication/SignInKakaoHelper.swift
  ABloom/ABloom/Info.plist
  ABloom/ABloom/Presentation/SignIn/SignInView.swift
  ABloom/ABloom/Presentation/SignIn/SignInViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/KakaoLoginLogo.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/KakaoLoginLogo.imageset/Shape 5.png
  ABloom/ABloom/Resources/Assets.xcassets/colors/Etc/Background.colorset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Etc/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/colors/Etc/KakaoYellow.colorset/Contents.json
  ABloom/ABloom/Resources/Extensions/Ex+Bundle.swift
Labels: Feat

#291 [Bug/#289] QA 반영
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
Labels: Bug
