Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2023-10, with the labels that each got.

#2 [Init] 프로젝트 초기 셋팅
  ABloom/.swiftlint.yml
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Assets.xcassets/AccentColor.colorset/Contents.json
  ABloom/ABloom/Assets.xcassets/AppIcon.appiconset/Contents.json
  ABloom/ABloom/Assets.xcassets/Contents.json
  ABloom/ABloom/Components/ComponetsMD.md
  ABloom/ABloom/Data/DataFolderMD.md
  ABloom/ABloom/Login/LoginMD.md
  ABloom/ABloom/Main/MainMD.md
  ABloom/ABloom/Main/MainView.swift
  ABloom/ABloom/Main/MainViewFeature.swift
  ABloom/ABloom/Preview Content/Preview Assets.xcassets/Contents.json
  ABloom/ABloom/TabBar/TabBarMD.md
Labels: Feat, 👍🏻 Merge Needed

#3 [Init] Remove TCA & 재정비
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Main/MainView.swift
  ABloom/ABloom/Main/MainViewFeature.swift
Labels: 🌱 Simple, 👍🏻 Merge Needed

#10 [Feat/#7] 유저 정보 입력화면을 구현합니다.
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Extension/Ex+View.swift
  ABloom/ABloom/Modifier/InputFieldModifier.swift
  ABloom/ABloom/Presentation/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/Registration/ViewModel/RegistrationViewModel.swift
Labels: Feat, 👀 Review Needed

#15 [Design/9] 디자인 컴포넌트 버튼, 챗버블 구현 & 파일명 및 구조 정리
  ABloom/.swiftlint.yml
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Assets.xcassets/Avartars/Contents.json
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle GradientBG.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle GradientBG.imageset/avatar_Female circle GradientBG@1x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle GradientBG.imageset/avatar_Female circle GradientBG@2x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle GradientBG.imageset/avatar_Female circle GradientBG@4x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle.imageset/avatar_Female circle@1x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle.imageset/avatar_Female circle@2x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Female circle.imageset/avatar_Female circle@4x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle GradientBG.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle GradientBG.imageset/avatar_Male circle GradientBG@1x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle GradientBG.imageset/avatar_Male circle GradientBG@2x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle GradientBG.imageset/avatar_Male circle GradientBG@4x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle.imageset/avatar_Male circle@1x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle.imageset/avatar_Male circle@2x.png
  ABloom/ABloom/Assets.xcassets/Avartars/avatar_Male circle.imageset/avatar_Male circle@4x.png
  ABloom/ABloom/Assets.xcassets/Icons/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.fill.imageset/Camera_fillVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/camera.fill.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.filled.circle_outline.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.filled.circle_outline.imageset/camera.filled_circle_outlineVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/camera.imageset/CameraVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/camera.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.light.imageset/Camera_lightVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/camera.light.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.outline.circle_outline.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.outline.circle_outline.imageset/camera.outline_circle_outlineVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/camera.white.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/camera.white.imageset/Group 1623Vector.svg
  ABloom/ABloom/Assets.xcassets/Icons/home.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/home.imageset/Home_fillVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/left.arrow.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/left.arrow.imageset/Left ArrowVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/order.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/order.imageset/Order_fillVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/pencil.write.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/pencil.write.imageset/Pencil_write_fillVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/return.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/return.imageset/Return_fillVector.svg
  ABloom/ABloom/Assets.xcassets/Icons/user.alt.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Icons/user.alt.imageset/User_alt_fillVector.svg
  ABloom/ABloom/Components/Buttons.swift
  ABloom/ABloom/Components/ChatBubbles.swift
  ABloom/ABloom/Components/InputFieldModifier.swift
  ABloom/ABloom/Extension/Ex+View.swift
  ABloom/ABloom/Extensions/CustomFonts.swift
  ABloom/ABloom/Extensions/DesignSystemEx.swift
  ABloom/ABloom/Extensions/Ex+Font.swift
  ABloom/ABloom/Extensions/Ex+Text.swift
  ABloom/ABloom/Extensions/Ex+View.swift
  ABloom/ABloom/Extensions/ExShape.swift
  ABloom/ABloom/Extensions/GradientColors.swift
  ABloom/ABloom/Extensions/Helpers.swift
  ABloom/ABloom/TabBar/TabBarView.swift
Labels: Design, 👀 Review Needed

#18 [Fix/#17] removed googleService
  ABloom/ABloom/GoogleService-Info.plist
Labels: Bug, 🚨 Emergency

#19 [Chore] 이전 리뷰 적용
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Components/Buttons.swift
  ABloom/ABloom/Extensions/Ex+Shape.swift
Labels: Bug, 👍🏻 Merge Needed

#20 [Feat/#11] 홈화면 레이아웃 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Assets.xcassets/Images/Contents.json
  ABloom/ABloom/Assets.xcassets/Images/TodayRecommendBG.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Images/TodayRecommendBG.imageset/image 3.png
  ABloom/ABloom/Assets.xcassets/Images/TodayRecommendBG.imageset/image 3@2x.png
  ABloom/ABloom/Assets.xcassets/Images/TodayRecommendBG.imageset/image 3@3x.png
  ABloom/ABloom/Assets.xcassets/Images/backgroundDefault.imageset/Contents.json
  ABloom/ABloom/Assets.xcassets/Images/backgroundDefault.imageset/Gradient BG 1.png
  ABloom/ABloom/Assets.xcassets/Images/backgroundDefault.imageset/Gradient BG 1@2x.png
  ABloom/ABloom/Assets.xcassets/Images/backgroundDefault.imageset/Gradient BG 1@3x.png
  ABloom/ABloom/Extensions/Ex+View.swift
  ABloom/ABloom/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Home/View/HomeView.swift
  ABloom/ABloom/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Main/MainView.swift
  ABloom/ABloom/Presentation/Home/HomeMD.md
  ABloom/ABloom/Presentation/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/TabBar/TabBarView.swift
Labels: Feat, 👍🏻 Merge Needed

#23 [Feat/#12] Firestore 유저
  .gitignore
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Authentication/SignInAppleHelper.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Login/LoginView.swift
  ABloom/ABloom/Login/LoginViewModel.swift
Labels: Feat, 👍🏻 Merge Needed

#30 [Design/#22] 유저 정보 입력 화면 디자인 적용
  ABloom/ABloom/Components/InputFieldModifier.swift
  ABloom/ABloom/Presentation/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/Registration/ViewModel/RegistrationViewModel.swift
Labels: Design, 👍🏻 Merge Needed

#36 [Feat/35] AnswerCheckView 구현 완료, 컴포넌트 생성 및 일부 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Components/ComponetsMD.md
  ABloom/ABloom/Resources/Extensions/Ex+Text.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
Labels: Feat, Design

#39 [Add/#38] 개인정보 처리방침 & 서비스 이용약관 URL 연동
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/PolicyView.swift
Labels: Feat, 👀 Review Needed

#40 [Chore/37] fontModifier 파라미터 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/MenuListNavigationItem.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/ToastView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/Buttons.swift
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Extensions/Ex+Text.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
Labels: Chore

#41 [Feat/35] SelectQuestionView 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
Labels: Feat, Design

#49 [Ref/#48] fontStyle 파라미터 명시 삭제
  ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Resources/Components/Buttons.swift
  ABloom/ABloom/Resources/Components/InputFields.swift
Labels: Bug, Ref

#50 [Feat/43] AnswerWriteView 구현, 관련 컴포넌트 수정
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Design

#52 [Feat/#46] 로그인뷰 레이아웃 적용
  ABloom/ABloom/Presentation/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Resources/Extensions/Ex+Shape.swift
Labels: Design

#54 [Feat/#47] 상대방과 연결 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check2.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Check3.png
  ABloom/ABloom/Resources/Assets.xcassets/Images/check.imageset/Contents.json
Labels: Feat, 👀 Review Needed

#56 [Fix/#47] 컨플릭트 오류 수정 및 로직 수정
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
Labels: Feat, 👀 Review Needed

#58 [Feat/#53] 로그인 뷰 - 개인정보처리방침, 이용약관 클릭 시 웹뷰 sheet 띄우기
  ABloom/ABloom/Presentation/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Login/LoginViewModel.swift
Labels: Feat, 🌱 Simple, 👀 Review Needed

#55 [Feat/51] Static 질문 Firebase 연동
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
Labels: Feat

#65 [Design/59] QuestionView 디자인 수정 및 완료
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Extensions/Ex+Shape.swift
  ABloom/ABloom/Resources/Extensions/Ex+View.swift
Labels: Bug, Design, 👍🏻 Merge Needed

#64 [Design/#61] 메인화면 디자인 적용
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/TabBar/TabBarView.swift
  ABloom/ABloom/Resources/Assets.xcassets/HomeDefaultImage.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/HomeDefaultImage.imageset/HomeDefaultImage.pdf
  ABloom/ABloom/Resources/Assets.xcassets/Icons/link.white.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/link.white.imageset/link.svg
  ABloom/ABloom/Resources/Assets.xcassets/Images/TodayRecommendAsset.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Images/TodayRecommendAsset.imageset/question_icon.pdf
Labels: Design, 👍🏻 Merge Needed

#67 [Feat/66] question empty view
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/pencilInText.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/pencilInText.imageset/pencilInText.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/pencilInText.imageset/pencilInText@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Icons/pencilInText.imageset/pencilInText@3x.png
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Extensions/Ex+Shape.swift
Labels: Design

#71 [Feat/#69] 내 정보 수정 구현
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
Labels: Feat, 👀 Review Needed

#73 [Feat/66] TextLimit과 경고창 구현
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Design, 👍🏻 Merge Needed

#68 [Design/#60] 커스텀 탭바 구현
  ABloom/ABloom/Presentation/CoreViews/TabBar/Tab.swift
  ABloom/ABloom/Presentation/CoreViews/TabBar/TabBarView.swift
Labels: Design, 👍🏻 Merge Needed

#74 [Feat/#72] 응답 기능 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Firebase/Model/DBStaticQuestionModel.swift
  ABloom/ABloom/Firebase/Model/DBUserModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
  ABloom/ABloom/Resources/Extensions/Ex+ Query.swift
Labels: Feat, 👀 Review Needed

#78 [Feat/#70] 홈화면 이미지 로컬 저장 및 불러오기 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/Home/ImageFileManager.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
Labels: Feat, 👀 Review Needed

#82 [Design/#81] 커스텀 네비게이션바 모디파이어 수정 및 뷰 적용
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/EmbedWebView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/PolicyView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
  ABloom/ABloom/Resources/Components/NavigationArrowLeft.swift
Labels: Design, 🌱 Simple, 👀 Review Needed

#85 [Feat/80] DB 연관 뷰 로직 수정
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Design

#84 [Feat/#77] 상대 답변에 따른 답변 메인 화면 로직 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
Labels: Feat, 👀 Review Needed

#86 [Design/83] 회원탈퇴 뷰 레이아웃 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
Labels: Design, 👀 Review Needed

#92 [Feat/#87] 상대방이 답변한 질문도 리스트에서 뜨지 않도록 수정
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
Labels: Feat, 👍🏻 Merge Needed

#94 [Bug/90] AnswerWrite Empty일 때, 처리
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
Labels: Bug, 👀 Review Needed

#95 [Chore/89] Add CategoryList
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_chatting.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_chatting.imageset/Property 1=circleIcon_isometric_chatting@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_chatting.imageset/Property 1=circleIcon_isometric_chatting@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_chatting.imageset/Property 1=circleIcon_isometric_chatting@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_location.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_location.imageset/Property 1=circleIcon_isometric_location@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_location.imageset/Property 1=circleIcon_isometric_location@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryCircleIcon(10)_2/circleIcon_isometric_location.imageset/Property 1=circleIcon_isometric_location@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_chatting.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_chatting.imageset/Property 1=squareIcon_isometric_chatting@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_chatting.imageset/Property 1=squareIcon_isometric_chatting@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_chatting.imageset/Property 1=squareIcon_isometric_chatting@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_location.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_location.imageset/Property 1=squareIcon_isometric_location@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_location.imageset/Property 1=squareIcon_isometric_location@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/CategoryImg/CategoryRectangleIcon/squareIcon_isometric_location.imageset/Property 1=squareIcon_isometric_location@3x.png
Labels: Chore, 🌱 Simple, 👀 Review Needed

#97 [Feat/#93] 상대방과 함께 작성한 문항 개수 홈에 표시
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
Labels: Feat

#107 [Bug/#106] HomeView partner > fiance 명칭 수정
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
Labels: Bug

#110 [Fix/#109] 질문 가져오기 로직 수정
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
Labels: Bug, 🚨 Emergency

#108 [Feat/100] Navigation&DarkMode
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Info.plist
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/NavigationModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Components/ChatBubbles.swift
Labels: Feat, Chore, 👀 Review Needed

#113 [Chore/111] ScrollView 수정, answers 빈 배열 수정(규니), 비었을 때 뷰 수정
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Resources/Components/QnAListItem.swift
Labels: Chore

#114 [Feat/#105] 추천질문 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Resources/Extensions/Ex+Date.swift
Labels: Feat, 👀 Review Needed

#115 [Feat/#112] 회원 탈퇴 기능 구현
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
Labels: Feat

#116 [Chore/111] ProgressView 핸들링
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Launch Screen.storyboard
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Background/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Background/SplashBack.imageset/00 Splash@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Background/SplashBack.imageset/00 Splash@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Background/SplashBack.imageset/00 Splash@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Background/SplashBack.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Icon/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Icon/SplashIcon.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Icon/SplashIcon.imageset/Splash Icon@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Icon/SplashIcon.imageset/Splash Icon@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Icon/SplashIcon.imageset/Splash Icon@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@3x.png
Labels: Chore

#119 [Fix/#117] 출시 전 다양한 이슈 해결
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Presentation/BoundaryViews/Login/LoginViewModel.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
Labels: Feat

#121 [Chore/91] Notification Inactivated
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/AppDelegate.swift
Labels: Chore

#124 [Bug/123] HomeNavigationIssue
  ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
Labels: Bug

#125 [Sprint1] 배포 준비 완료.
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
Labels: Feat
