Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2023-12, with the labels that each got.

#292 [Bug] QA 대응
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Splash@3x.png
Labels: Bug, Feat

#297 [Feat/#296] Mixpanel 관련 기능 업데이트
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionView1.0.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginMD.md
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ImageFileManager.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/MenuListNavigationItem.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/PolicyView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/SelectQuestionView1.0.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/NavigationModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/SelectQuestionViewModel1.0.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/Tab.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarMD.md
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingTabView.swift
  ABloom/ABloom/Presentation/SignIn/SignInViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
  ABloom/ABloom/Resources/Utilities/MixpanelManager.swift
  ABloom/ABloom/Resources/Utilities/ToastView.swift
Labels: Feat

#300 [Feat/#299] 문답리스트뷰 상대방없을 시 프로필 빨간 점 추가
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
Labels: Feat, 👀 Review Needed

#301 [Feat] 2.0.1 업데이트 준비 완료
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/AppDelegate.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionView1.0.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginMD.md
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Login/LoginView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/View/RegistrationView.swift
  ABloom/ABloom/Presentation/1.0/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ImageFileManager.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Home/ViewModel/HomeViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/MenuView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/MenuListNavigationItem.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/PolicyView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerCheckView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/AnswerWriteView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/QuestionMainView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/SelectQuestionView1.0.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/TipView.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/NavigationModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/SelectQuestionViewModel1.0.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/Tab.swift
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarMD.md
  ABloom/ABloom/Presentation/1.0/CoreViews/TabBar/TabBarView.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
  ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingTabView.swift
  ABloom/ABloom/Presentation/SignIn/SignInViewModel.swift
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
  ABloom/ABloom/Resources/Utilities/MixpanelManager.swift
  ABloom/ABloom/Resources/Utilities/ToastView.swift
Labels: Feat
