Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2024-02, with the labels that each got.

#323 [Fix] HOT FIX - 애플 로그인 시 사용자 이름 요청 제거
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Authentication/SignInAppleHelper.swift
Labels: 🚨 Emergency

#319 [Feat/#318] 온보딩 플로우 삭제
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingPageView.swift
  ABloom/ABloom/Presentation/Onboarding/OnboardingTabView.swift
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_1.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_1.imageset/onboarding_1@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_1.imageset/onboarding_1@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_1.imageset/onboarding_1@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_2.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_2.imageset/onboarding_2@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_2.imageset/onboarding_2@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_2.imageset/onboarding_2@3x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_3.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_3.imageset/onboarding_3@1x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_3.imageset/onboarding_3@2x.png
  ABloom/ABloom/Resources/Assets.xcassets/Onboarding/onboarding_3.imageset/onboarding_3@3x.png
Labels: Feat

#324 [Fix] 애플로그인시 이름 요청 제거 (핫픽스 반영)
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Authentication/SignInAppleHelper.swift
Labels: Bug

#321 [Bug/#320] 회원가입 이름 입력창 줄어드는 버그 수정
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
  ABloom/ABloom/Resources/Utilities/ReactionType.swift
Labels: Bug, 🌱 Simple, 👀 Review Needed

#330 [Design/#328] 만 14세 이상 확인 버튼 추가
  ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift
  ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
Labels: Design
