Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2024-04, with the labels that each got.

#347 [Bug/#346] 반응 수정 적용
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
Labels: Bug, 🚨 Emergency, 🌱 Simple, 👀 Review Needed

#344 [Bug/#340] JS 코드 수정
  FirebaseFunction/functions/index.js
Labels: Bug, 🌱 Simple, 👀 Review Needed

#352 [v2.0.3] 배포 완료
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
Labels: Feat

#355 [Feat/#354] 알림-DB 업데이트 로직 수정
  ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
  ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
  FirebaseFunction/functions/index.js
Labels: Bug
