Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2024-01, with the labels that each got.

#304 [Feat/#303] TextField 영역확장 (Editor로 바꿈)
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
Labels: Feat

#307 removed cached&mixPanelToken
  .gitignore
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/AppDelegate.swift
Labels: Chore

#310 [Bug/#309] 연결 시 상대방 기기에는 반영되지 않는 버그
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift
Labels: Bug, 👀 Review Needed

#308 [Feat/#302] 구글 로그인/로그아웃/회원탈퇴 구현
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/ABloomApp.swift
  ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
  ABloom/ABloom/Firebase/Authentication/SignInGoogleHelper.swift
  ABloom/ABloom/Info.plist
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/SignIn/SignInView.swift
  ABloom/ABloom/Presentation/SignIn/SignInViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/HomeDefaultImage.imageset/HomeDefaultImage.pdf
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/AppleLoginLogo.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/AppleLoginLogo.imageset/icon_apple_symbol.pdf
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/GoogleLoginLogo.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/GoogleLoginLogo.imageset/GoogleLogo.pdf
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/KakaoLoginLogo.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/LoginLogo/KakaoLoginLogo.imageset/Shape 5.png
  ABloom/ABloom/Resources/Assets.xcassets/colors/Etc/GoogleGray.colorset/Contents.json
Labels: Feat, 👀 Review Needed

#311 [Design/#306] scrollArea 늘리기
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
Labels: Design
