Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2024-06, with the labels that each got.

#364 [Chore/#363] v1에서 Remove Reference로 남아있던 파일/폴더 삭제
  ABloom/ABloom/Presentation/1.0/CoreViews/Menu/SubViews/Components/MenuListItem.swift
  ABloom/ABloom/Presentation/Home/HomeMD.md
  ABloom/ABloom/Presentation/Home/View/HomeRecommendView.swift
  ABloom/ABloom/Presentation/Home/View/HomeView.swift
  ABloom/ABloom/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: Chore

#366 [Feat] 질문 선택 시 전송되는 프로퍼티 추가
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Resources/Utilities/MixpanelManager.swift
Labels: Feat

#369 [2.0.4] 릴리즈 수정사항 반영
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
  ABloom/ABloom/Resources/Utilities/MixpanelManager.swift
Labels: Bug, Feat
