Repository DeveloperAcademy-POSTECH/MacC-Team16-ABloom, pull requests merged in 2024-07, with the labels that each got.

#368 [Feat/#367] 리뷰팝업추가
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
  ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
Labels: Feat, 👀 Review Needed

#372 [Feat/#371] 공지 불러오는 기능 추가
  ABloom/ABloom.xcodeproj/project.pbxproj
  ABloom/ABloom/Firebase/Firestore/AnnouncementManager.swift
  ABloom/ABloom/Firebase/Model/DBAnnouncementModel.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
  ABloom/ABloom/Resources/Assets.xcassets/Icons/notice.imageset/Contents.json
  ABloom/ABloom/Resources/Assets.xcassets/Icons/notice.imageset/notice.svg
  ABloom/ABloom/Resources/Extensions/Ex+Font.swift
Labels: Feat

#374 [Bug/#373] 로그인 후 바로 문답 생성시 화면에 바로 보여지지 않는 버그 픽스
  ABloom/ABloom/Firebase/Firestore/UserManager.swift
  ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
Labels: Bug, 🌱 Simple
